### PR TITLE
Builder.WithPort  not working

### PR DESCRIPTION
**Pull request by aNutForAJarOfTuna**
"withPort" in Builder is not setting the port, but using default port 9042.

### CODE REVIEW

**Comment by jorgebay** [comment]
Nice catch, I think this was bug was caused by the introduction of the address translator #42, as the contact points are now ip endpoints.

I will review it shortly.

**Comment by aNutForAJarOfTuna** [comment]
Thanks jorgebay, may I know normally how long would the changes in master reflect on nuget packages ?

**Comment by jorgebay** [comment]
It depends...

Could you also fix the use of `_ports` in the `AddContactPoints()` method and git squash your commits?

It should be something like:
```csharp
public Builder AddContactPoint(IPAddress address)
{
  AddContactPoint(new IPEndPoint(address, _port));
  //Use _port                              ˆˆˆˆ
  return this;
}
```

I'll try to include it in the upcoming version 2.5.1.

**Comment by aNutForAJarOfTuna** [comment]
Ok. So do we want the interface to set different port for different contact point in the same line like this: 

builder
.AddContactPoint("addr1").WithPort(9140)
.AddContactPoint("addr2").WithPort(9240)
...

or the last "WithPort" would override the previous ports in the contact points?

**Comment by jorgebay** [comment]
The port setting is for all nodes of the cluster, the driver will also use it when discovering the rest of the nodes in the cluster.
In the following example:
```csharp
builder
  .WithPort(9011)
  .AddContactPoints("host1", "host2");
```
If there is a host3 discovered by the driver, it will use the port setting as well.
For different port configurations and stuff like that, the user must create an AddressTranslator.

**Comment by aNutForAJarOfTuna** [comment]
Sounds good, just made a small change as you state and should be good to merge now.

**Comment by jorgebay** [comment]
I've cherry picked it to master: 3a750876e185a81f0b759fcf7102d6edbb2c539e.
Also, I've found another bug in the method `AddContactPoints()` method, fixed in 0faf3cb582eb11de15abafe27bf5baaa76c96e1f, with additional tests.

Thanks!

**Comment by jorgebay** [comment]
I've also changed `List<T>.ForEach()` call to a language `foreach` iteration as `ForEach()` method is [not supported in all platforms](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,583).

**Pull request closed without merging**
