### PR TITLE
Use OptionsRequest for heartbeats

### PR DESCRIPTION
**Pull request by jorgebay**
Use OPTIONS request for heartbeats and convert few tests to async
execution.

### CODE REVIEW

**Comment by jorgebay** [comment]
cc @landim

**Comment by landim** [comment]
The errors at CI builds are not related to this PR

**Comment by jorgebay** [comment]
> One side note. I think that simulacron would be beneficial to verify the amount of heartbeat request sent to server. wdyt?

Its a good idea, does simulacron logs it? How can we retrieve it?

**Comment by landim** [comment]
You can get all the requests received by the cluster/dc/node using this method: https://github.com/datastax/csharp-driver/blob/master/src/Cassandra.IntegrationTests/TestClusterManagement/Simulacron/SimulacronBase.cs#L93

**Pull request merged**
