### PR TITLE
Type conversion for UDT fields and tests

### PR DESCRIPTION
**Pull request by jorgebay**
To track and include tests for #260 by @ElliotSis (CSHARP-381).

CC @landim

### CODE REVIEW

**Comment by ElliotSis** [comment]
I wrote some test and the conversion from DateTime to DateTimeOffset seems to fail.
The rest appears to work.

**Comment by landim** [comment]
Jira ticket created regarding the tests https://datastax-oss.atlassian.net/browse/CSHARP-509

**Comment by jorgebay** [comment]
@landim any news? can we tackle this after v3.3.2?

**Comment by landim** [comment]
Tests at https://github.com/datastax/csharp-driver/pull/338 (still in progress)

**Comment by jorgebay** [comment]
It was done from the CSHARP-381-tests branch, I'm closing this one.

**Pull request closed without merging**
