### PR TITLE
Support prepare on all nodes and re-prepare on UP

### PR DESCRIPTION
**Pull request by jorgebay**
- Introduce `PrepareHandler`.
- Simplify `RequestHandler`, which now only handles `QUERY`, `EXECUTE` and `BATCH` requests.
- Test query preparation using simulacron.

### CODE REVIEW

**Comment by jorgebay** [comment]
There is a failure related to timeouts using simulacron, I'm not sure the underlying reason (does `delay_in_ms` works on simulacron?)...

**Comment by landim** [comment]
It should work, I will make some tests

**Comment by landim** [comment]
It should work, I'll take a look at simulacron code

**Comment by landim** [comment]
Rebased with master. Your test looks good. The issue is on simulacron side (as you suspected. Prepare command is handled in a special way and it is ignoring the delayInMs. I already created a bug: https://github.com/datastax/simulacron/issues/23 and also pushed the fix. I will keep an eye on it and update the simulacron version on our CI as soon as it is released.

**Comment by jorgebay** [comment]
I've rebased it against master and add ignore attribute for test related to datastax/simulacron#23.

**Comment by landim** [comment]
looks good to me. 👍

**Pull request merged**
