### PR TITLE
LINQ support for writetime() function

### PR DESCRIPTION
**Pull request by bastianeicher**
This adds support for LINQ queries like:

```csharp
var result = myTable
    .Where(x => x.Id == "abc")
    .Select(x => new {WriteTime = CqlFunction.WriteTime(x.MyColumn)})
    .Execute();
```

They will be transformed to CQL like this:

```cql
SELECT WRITETIME(MyColumn) FROM my_table;
```

### CODE REVIEW

**Comment by joao-r-reis** [comment]
Hi, thanks for your contribution. Have you signed our [CLA](https://cla.datastax.com)?

**Comment by bastianeicher** [comment]
> Hi, thanks for your contribution. Have you signed our [CLA](https://cla.datastax.com)?

Yes. :)

**Comment by joao-r-reis** [comment]
justfyi: [C# Driver 3.19.0 is now GA](https://groups.google.com/a/lists.datastax.com/g/csharp-driver-user/c/IuuCltBoQ8g) (which includes this feature)

**Comment by bastianeicher** [comment]
Hello @joao-r-reis,

thank you very much for merging and releasing this change so swiftly! :)

Unfortunately, I overlooked something and chose the wrong return type for the new method. :( I've created a follow-up PR to fix this: #581

**Pull request merged**
