### PR TITLE
.NET Core support

### PR DESCRIPTION
**Pull request by jorgebay**
This is a work in progress, available for early review and testing.

Supports building and running tests using both .NET Framework toolchain (msbuild) and .NET Core (dotnet cli). msbuild will still be supported until .NET Core toolchain gets a general availability release (currently in preview mode).

.NET Framework v4.0 support is dropped, making v4.5 the lower supported version.

Some limitations:
- Moq is not supported for test (the support for .NET Core in Moq is still underway).
- Lz4 compression is not supported for now ([lz4net](https://www.nuget.org/packages/lz4net/) does not support .NET Core yet, see https://github.com/MiloszKrajewski/lz4net/issues/9) 

In progress / done:
- [x] Appveyor .NET Core builds (unit and integration tests) for net452 and netstandard
- [x] TravisCI .NET Core builds for netstandard
- [x] Several broken integration tests under ".netstandard1.5"
- [x] Packaging
- [x] Test sandcastle API docs generation

### CODE REVIEW

**Comment by landim** [comment]
so far, the integration tests are running without major flaws. :+1:

**Comment by jorgebay** [comment]
When preparing scripts and project.json for nuget packaging and publishing, I bumped into https://github.com/dotnet/cli/issues/3040.
Created a workaround script `build/pack.bat` that will have to be used until the issue on dotnet-cli gets fixed.

**Comment by jorgebay** [comment]
Part of the appveyor build matrix is failing due to a bug in [Cassandra on Windows](https://issues.apache.org/jira/browse/CASSANDRA-12278), otherwise it looks good.

**Comment by jorgebay** [comment]
Currently all tests are running smoothly, I copy some numbers:

.NET Framework 4.5: 
- Unit tests: 411
- Integration tests: 564

.Net Core 1.0:
- Unit tests: 224
- Integration tests: 557

There are fewer test that run against .NET Core because Moq doesn't support it yet.

The integration tests run against different Cassandra versions on appveyor.
Let's wait to see what's the behaviour of linux builds on Jenkins.

**Comment by landim** [comment]
Looking good @jorgebay . I am working on jenkins side. So far, the only issue that I am facing its regarding the nunit3 report (which is not compatible). More details at the PR I will create later.

**Comment by landim** [comment]
:+1: LGTM

**Comment by SonOfSam** [comment]
quick question, with these merge this driver will support .net core? or still on beta?

**Comment by jorgebay** [comment]
@afoliaco The driver will support .NET Core 1.0 and .NET Framework 4.5 in version 3.1 of the driver. We will first release a beta 3.1 version of the driver and then a general availability of 3.1 (aka RTM).

**Comment by jorgebay** [comment]
Merged!
Landed in 0b92f67cd9a833a74c24787b673547dac4fe5795 in the 3.1 branch.

**Comment by MiloszKrajewski** [comment]
lz4net has experimental support for .NET core now

**Comment by jorgebay** [comment]
Nice! Thanks @MiloszKrajewski , we will give it a try.

**Comment by sgatenby** [comment]
Great news! My team waiting anxiously for this.

**Pull request closed without merging**
