### PR TITLE
Bugfix: Select anonymous type containing a nullable column

### PR DESCRIPTION
**Pull request by oguimbal**
I ran into a quite anoying issue.

Suppose you have this schema

    create table mytable(id stringPRIMARY KEY, mydouble double);
    insert into mytable (id,mydouble) values ('id1',0);
    insert into mytable (id,mydouble) values ('id2',1);

Mapped to class:

    public class MyTable{ 
        public string Id{get;set;} 
        public double? MyDouble{get;set;}  // nb: This is nullable
    }

And you perform this request:

    myTable.Select(x=>new{x.Id,x.MyDouble}).ToArray();

Everything should be fine.
But now, insert a null value

    insert into mytable (id,mydouble) values ('id3',null);

...and perform the same request.

Exception thrown:
**Cannot convert null to System.Double because it is a value type, try using Nullable<System.Double>**

This commit fixes it

### CODE REVIEW

**Comment by jorgebay** [comment]
Nice fix!

Could you clean your commit to avoid reformatting existing code to avoid messing up with history?

I created [Jira ticket CSHARP-346](https://datastax-oss.atlassian.net/browse/CSHARP-346) to track this issue.

**Comment by oguimbal** [comment]
@jorgebay done

**Comment by oguimbal** [comment]
Not sure to understand why this test fails on  Travis CI build: SetDown_Should_Get_The_Next_Delay_Once_The_Time_Passes

(... works on my machine)

**Comment by jorgebay** [comment]
I asked travis to rebuild it, the test result is not conclusive.

**Comment by oguimbal** [comment]
Not conclusive ?
It seems to pass now... doesnt it ?
In the test:
   
      Thread.Sleep(3000); 

That must be a timing/concurrency issue...

**Comment by jorgebay** [comment]
Yes, it is.

I meant that the test failing does not prove that there is an issue: the test needs to be fixed not the code :smile:

**Pull request merged**
