### PR TITLE
Don't mark host down while one connection is active

### PR DESCRIPTION
**Pull request by jorgebay**
Refactor pool to allow partially connected pools and prevent nodes to be marked as down until all connections (from all connection pools) have been closed.

### CODE REVIEW

**Comment by jorgebay** [comment]
@landim scassandra integration for tests is looking good. As the implementation of the new host pool involves a lot of changes, do you mind integrating scassandra in a different branch?

**Comment by jorgebay** [comment]
Squashed commits.

**Comment by jorgebay** [comment]
There is a failure in the [last appveyor build](https://ci.appveyor.com/project/DataStax/csharp-driver/build/CSHARP-274-651/job/4hjahtcvyw2c4uku) that surfaced an issue in the implementation of the logger (CSHARP-171).

I'm going to fix it on this branch.

**Comment by jorgebay** [comment]
After several builds, there is another failure: https://ci.appveyor.com/project/DataStax/csharp-driver/build/CSHARP-274-708/job/qyeyrdfdc6dk8xrh

It looks like a driver issue, I'm looking into it.

**Comment by jorgebay** [comment]
The issue [described here](https://github.com/datastax/csharp-driver/pull/267#issuecomment-266390177) is now fixed.

I've set the reconnection test to be repeated 20 times per build on f3a4069 and it passes (executed total of 400 times on Jenkins and 120 on appveyor).

I've restore to only execute it few times per build.

I've also added several test fixes. I will merge it once the last build finishes.

**Comment by ablanchet** [comment]
Hi @jorgebay 

It seems that you merged the implementations of two properties on Host : `IsConsiderablyUp` and `IsUp` now return the same value (which is `IsUp`). 

I think it could be nice to mark the `IsConsiderablyUp` property as obsolete - and remove it from good for the next breaking changes release. 

I checked in the java implem and I can't find the same _considerably_ thing, only a  [`getIsUp` method](https://github.com/datastax/java-driver/blob/3.x/driver-core/src/main/java/com/datastax/driver/core/Host.java#L312)

**Comment by jorgebay** [comment]
You are right about deprecating `IsConsiderablyUp`, it was previously used to determine if reconnection attempts can be made in case it was down.
I would soft-deprecate it, I'm very conservative about using `[Obsolete]` in a minor version: for users with "Warning as error" setting it will mean a breaking change.

We can now include a paragraph in the xmldoc, saying something like: `"This property is going to be removed in future versions, use IsUp instead"` and in the next major version, we can mark it as obsolete.

Would you like to send a pull request for it?

**Comment by ablanchet** [comment]
Yes I will push a PR later today. 
And you're right about the obsolete attribute, I'll just add a comment and leave the breaking change for a future version.

**Pull request merged**
