### PR TITLE
CSHARP-989 Change return type of CqlFunction.WriteTime() to DateTimeOffset

### PR DESCRIPTION
**Pull request by bastianeicher**

### CODE REVIEW

**Comment by joao-r-reis** [comment]
Hmm I will take a quick look at this after the holidays is that ok? We will probably want to add an integration test to make sure it works correctly this time.

**Comment by joao-r-reis** [comment]
Also, the build is failing.

**Comment by bastianeicher** [comment]
> Hmm I will take a quick look at this after the holidays is that ok? We will probably want to add an integration test to make sure it works correctly this time.

Absolutely. Happy holidays. :)

**Comment by joao-r-reis** [comment]
> Absolutely. Happy holidays. :)

You too!

**Comment by joao-r-reis** [comment]
> Absolutely. Happy holidays. :)

Happy holidays!

**Comment by bastianeicher** [comment]
I've fixed the build.

Could you give me some pointers how to get started on an integration test for this feature?

**Pull request merged**
