### PR TITLE
Snappy bad position index format fix

### PR DESCRIPTION
**Pull request by marcelvillet**
Probably a Java port mistake?

### CODE REVIEW

**Comment by jorgebay** [comment]
Nice catch!
yes, it was introducing while [porting snappy decompression back in v1][1].

Did you intended to include just a9ad168 in the pull request?
If so, do you want to rebase or should I go ahead and cherry pick a9ad168?

[1]: https://github.com/datastax/csharp-driver/blob/1.0/References/Snappy/SnappyInternalUtils.cs#L135

**Comment by marcelvillet** [comment]
You can cherry pick, thanks. 

On 2016-10-27 15:27, Jorge Bay Gondra wrote: 

> Nice catch!
> yes, it was introducing while porting snappy decompression back in v1 [1]. 
> 
> Did you intended to include just a9ad168 [2] in the pull request?
> If so, do you want to rebase or should I go ahead and cherry pick a9ad168 [2]? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1]
https://github.com/datastax/csharp-driver/blob/1.0/References/Snappy/SnappyInternalUtils.cs#L135
[2]
https://github.com/datastax/csharp-driver/commit/a9ad16877ed5248ed1e5d6144ab6db7d77266ce5
[3]
https://github.com/datastax/csharp-driver/pull/265#issuecomment-256640034
[4]

**Comment by jorgebay** [comment]
Will do, thanks!

**Comment by jorgebay** [comment]
Landed in 9c7f990fe06f7f1aa9b24aef5ea96bb9370a403f . Thanks!

**Pull request closed without merging**
