### PR TITLE
Fix for concurrency bug CSHARP-709

### PR DESCRIPTION
**Pull request by si31**
This is a fix for ticket https://datastax-oss.atlassian.net/browse/CSHARP-709

### CODE REVIEW

**Comment by jorgebay** [comment]
Nice troubleshooting to come to the conclusion on the ticket.

On the first pass, it looks good. I'll look into it with more detail during this week.

**Comment by jorgebay** [comment]
Sorry @si31, I'll look at it today/tomorrow.

**Comment by si31** [comment]
Ahh yes of course, you're right. It would require an atomic operation.

I would suggest, within the cancelled check in TimerTick, to try to remove it from cancelled timeouts using the TryDequeue operation. Then you shouldn't get the error, but the try catch is probably a good idea anyway.

Thanks a lot for looking at this.

**Comment by jorgebay** [comment]
Remember that `TimerTick()` is executed on an IO thread and we need to get out of `TimerTick()` as as soon as possible to try to have predictable performance.

I think using a try/catch on `RemoveCancelled()` is safer choice than looping over the cancelled timeouts again.

**Comment by si31** [comment]
Cool, it would be great if that you could add that change asap, I've updated this pr with it if that's easier.

Thanks again

**Comment by jorgebay** [comment]
I'm waiting for CI to finish and I'll merge it.

**Comment by jorgebay** [comment]
Thanks @si31 for your contribution and the effort in finding the underlying reason of the bug! 🎉

**Pull request merged**
