### PR TITLE
add to ColumnDesc IsStatic info.

### PR DESCRIPTION
**Pull request by eLVampa**

### CODE REVIEW

**Comment by eLVampa** [comment]
I want to know if the column is static. This is useful to analyze the current table schema and checking of mapping from code.

Sorry, my English is not so good.

**Comment by jorgebay** [comment]
Looks like a nice addition, thanks @eLVampa !

I'll make a full review tomorrow.

**Comment by eLVampa** [comment]
Hi, @jorgebay. 

It's my first PR! And that's why I'm worried. 
Do I need to finish something?

**Comment by jorgebay** [comment]
No need to worry :)
I'll look at it today or Monday, sorry for the delay.

**Comment by jorgebay** [comment]
Great contribution @eLVampa 🎉 !

Kudos for adding it to both `SchemaParserV1` and `SchemaParserV2` and creating unit tests.

**Comment by eLVampa** [comment]
It's great! Thanks you, @jorgebay.

It's small contribution, but important for me.

**Pull request merged**
